### ISSUE TITLE
Change "Column 2:  ESP32 IO29/CS" to "Column 2:  ESP32 IO5/CS"

### ISSUE THREAD

**Issue by EsserPrototyping** [blackketter/teensy4_esp32_breakout#1]
Hi!
I have seen that you have mixed up a Pin-Name / Pin-Number definition in your readme.md IO29/CS is ESP32 IO5/CS on the ESP32.

However - Nice project!
Is it working how you´ve intended? I´m making a Teensy 4.1 Test board myself and was wondering if the handling of the reset and enable pin is working fine, because on a lot ESP32 boards, there is not enought capacity on the enable pin in conjunction with the - often used - CP2104 serial IC, so the boot button is needed. But maybe this is nonsens if toggled by two pins of the Teensy directly.
I´m more experienced with ESP32 than Teensy..
Keep on! Steffen

**Comment by blackketter** [comment]
Good find!  Thanks, Steffen.  I fixed the README.

The board worked for me, but I haven't used it much beyond the very first initial testing using the teensy to drive the EN and IO0 pins.
